settings:
  skin: dark
preloader:
  logo:
    image: assets/img/ober_logo.png
    alt: ''
header:
  logo:
    image: assets/img/ober_logo.png
    alt: Joé Wilson
social:
  - name: Facebook
    icon: fab fa-dribbble
    url: http://facebook.com/carlosjlerma
  - name: Twitter
    icon: fab fa-twitter
    url: http://twitter.com/carlosjlerma
  - name: Instagram
    icon: fab fa-instagram
    url: http://instagram.com/cjlerma
footer:
  copyright: Carlos Lerma. All Rights Reserved
portfolio:
  filters:
    - name: UI UX Design
      slug: ui-ux-design
    - name: Photography
      slug: photography
    - name: Development
      slug: development
    - name: Branding
      slug: branding
