# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  skin: "light" # select initial sking option: "light" or "dark"

### Preloader
preloader:
  logo:
    image: "assets/img/ober_logo.png"
    alt: ""

### Header
header:
  logo:
    image: "assets/img/ober_logo.png"
    alt: "Joé Wilson"

### Social
social:
  - name: "Facebook"
    icon: "fab fa-dribbble"
    url: "http://facebook.com/carlosjlerma"

  - name: "Twitter"
    icon: "fab fa-twitter"
    url: "http://twitter.com/carlosjlerma"

  - name: "Instagram"
    icon: "fab fa-instagram"
    url: "http://instagram.com/cjlerma"

### Footer
footer:
  copyright: "Carlos Lerma. All Rights Reserved"

### Portfolio Filters Settings
portfolio:
  filters:
    - name: "UI UX Design"
      slug: "ui-ux-design"

    - name: "Photography"
      slug: "photography"

    - name: "Development"
      slug: "development"

    - name: "Branding"
      slug: "branding"
